package com.timecoin.wallet.ui.screen

import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.text.KeyboardActions
import androidx.compose.foundation.text.KeyboardOptions
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Check
import androidx.compose.material.icons.filled.Close
import androidx.compose.material.icons.filled.Print
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.focus.FocusRequester
import androidx.compose.ui.focus.focusRequester
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.input.*
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.timecoin.wallet.crypto.MnemonicHelper
import com.timecoin.wallet.service.WalletService

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun MnemonicSetupScreen(service: WalletService) {
    var mnemonic by remember { mutableStateOf("") }
    var isGenerated by remember { mutableStateOf(false) }
    var use24Words by remember { mutableStateOf(false) }
    var isRestoring by remember { mutableStateOf(false) }
    var restoreWordCount by remember { mutableStateOf(12) }
    val words = remember { mutableStateListOf(*Array(24) { "" }) }
    val focusRequesters = remember { List(24) { FocusRequester() } }

    // Per-word validation
    val wordValidities = (0 until restoreWordCount).map { i ->
        when {
            words[i].isBlank() -> null
            !MnemonicHelper.hasWordList -> null
            else -> MnemonicHelper.isValidWord(words[i])
        }
    }
    val validCount = wordValidities.count { it == true }
    val allFilled = (0 until restoreWordCount).all { words[it].isNotBlank() }
    val phraseValid = if (allFilled) {
        val phrase = (0 until restoreWordCount).joinToString(" ") { words[it] }
        MnemonicHelper.validate(phrase)
    } else false

    val effectiveMnemonic = when {
        isRestoring && phraseValid -> (0 until restoreWordCount).joinToString(" ") { words[it] }
        isGenerated -> mnemonic
        else -> ""
    }
    val showPasswordSection = isGenerated || (isRestoring && phraseValid)

    Column(
        modifier = Modifier
            .fillMaxSize()
            .padding(24.dp)
            .verticalScroll(rememberScrollState()),
        horizontalAlignment = Alignment.CenterHorizontally,
    ) {
        Text(
            text = if (isRestoring) "Restore Wallet" else "Create Wallet",
            style = MaterialTheme.typography.headlineMedium,
            fontWeight = FontWeight.Bold,
        )
        Spacer(Modifier.height(24.dp))

        if (!isRestoring && !isGenerated) {
            // Generate new mnemonic
            Row(verticalAlignment = Alignment.CenterVertically) {
                Text("24-word mnemonic")
                Spacer(Modifier.width(8.dp))
                Switch(checked = use24Words, onCheckedChange = { use24Words = it })
            }
            Spacer(Modifier.height(16.dp))

            Button(onClick = {
                mnemonic = MnemonicHelper.generate(if (use24Words) 24 else 12)
                isGenerated = true
            }) {
                Text("Generate Mnemonic")
            }

            Spacer(Modifier.height(24.dp))
            TextButton(onClick = { isRestoring = true }) {
                Text("I already have a mnemonic phrase")
            }
        }

        if (isGenerated && !isRestoring) {
            // Display generated mnemonic
            Card(
                modifier = Modifier.fillMaxWidth(),
                colors = CardDefaults.cardColors(
                    containerColor = MaterialTheme.colorScheme.primaryContainer,
                ),
            ) {
                Column(Modifier.padding(16.dp)) {
                    Text(
                        text = "⚠ Write down these words and keep them safe!",
                        style = MaterialTheme.typography.labelLarge,
                        color = MaterialTheme.colorScheme.error,
                        fontWeight = FontWeight.Bold,
                    )
                    Spacer(Modifier.height(12.dp))
                    val displayWords = mnemonic.split(" ")
                    for (i in displayWords.indices step 3) {
                        Row(Modifier.fillMaxWidth()) {
                            for (j in 0 until 3) {
                                val idx = i + j
                                if (idx < displayWords.size) {
                                    Text(
                                        text = "${idx + 1}. ${displayWords[idx]}",
                                        modifier = Modifier.weight(1f),
                                        style = MaterialTheme.typography.bodyLarge,
                                        fontWeight = FontWeight.Medium,
                                    )
                                }
                            }
                        }
                        Spacer(Modifier.height(4.dp))
                    }
                }
            }
        }

        if (isRestoring) {
            // Word count selector
            Row(
                modifier = Modifier.fillMaxWidth(),
                horizontalArrangement = Arrangement.Center,
                verticalAlignment = Alignment.CenterVertically,
            ) {
                FilterChip(
                    selected = restoreWordCount == 12,
                    onClick = {
                        restoreWordCount = 12
                        for (i in 12 until 24) words[i] = ""
                    },
                    label = { Text("12 Words") },
                )
                Spacer(Modifier.width(12.dp))
                FilterChip(
                    selected = restoreWordCount == 24,
                    onClick = { restoreWordCount = 24 },
                    label = { Text("24 Words") },
                )
            }
            Spacer(Modifier.height(16.dp))

            // Numbered word input grid (2 columns: 1-6 left, 7-12 right)
            val halfCount = restoreWordCount / 2
            for (row in 0 until halfCount) {
                Row(
                    modifier = Modifier.fillMaxWidth(),
                    horizontalArrangement = Arrangement.spacedBy(8.dp),
                ) {
                    val leftIdx = row
                    val rightIdx = row + halfCount
                        MnemonicWordInput(
                            number = leftIdx + 1,
                            value = words[leftIdx],
                            onValueChange = { newValue ->
                                if (" " in newValue || "\n" in newValue || "\t" in newValue) {
                                    val parts = newValue.split("\\s+".toRegex())
                                        .filter { it.isNotBlank() }
                                    if (parts.isEmpty()) return@MnemonicWordInput
                                    for ((j, word) in parts.withIndex()) {
                                        if (leftIdx + j < restoreWordCount) {
                                            words[leftIdx + j] = word.lowercase()
                                        }
                                    }
                                    val nextIdx = (leftIdx + parts.size)
                                        .coerceAtMost(restoreWordCount - 1)
                                    try {
                                        focusRequesters[nextIdx].requestFocus()
                                    } catch (_: Exception) {}
                                } else {
                                    words[leftIdx] = newValue.lowercase().trim()
                                }
                            },
                            isValid = wordValidities.getOrNull(leftIdx),
                            focusRequester = focusRequesters[leftIdx],
                            isLastField = leftIdx == restoreWordCount - 1,
                            onNext = {
                                val next = leftIdx + 1
                                if (next < restoreWordCount) {
                                    try {
                                        focusRequesters[next].requestFocus()
                                    } catch (_: Exception) {}
                                }
                            },
                            modifier = Modifier.weight(1f),
                        )
                        MnemonicWordInput(
                            number = rightIdx + 1,
                            value = words[rightIdx],
                            onValueChange = { newValue ->
                                if (" " in newValue || "\n" in newValue || "\t" in newValue) {
                                    val parts = newValue.split("\\s+".toRegex())
                                        .filter { it.isNotBlank() }
                                    if (parts.isEmpty()) return@MnemonicWordInput
                                    for ((j, word) in parts.withIndex()) {
                                        if (rightIdx + j < restoreWordCount) {
                                            words[rightIdx + j] = word.lowercase()
                                        }
                                    }
                                    val nextIdx = (rightIdx + parts.size)
                                        .coerceAtMost(restoreWordCount - 1)
                                    try {
                                        focusRequesters[nextIdx].requestFocus()
                                    } catch (_: Exception) {}
                                } else {
                                    words[rightIdx] = newValue.lowercase().trim()
                                }
                            },
                            isValid = wordValidities.getOrNull(rightIdx),
                            focusRequester = focusRequesters[rightIdx],
                            isLastField = rightIdx == restoreWordCount - 1,
                            onNext = {
                                val next = rightIdx + 1
                                if (next < restoreWordCount) {
                                    try {
                                        focusRequesters[next].requestFocus()
                                    } catch (_: Exception) {}
                                }
                            },
                            modifier = Modifier.weight(1f),
                        )
                }
                Spacer(Modifier.height(4.dp))
            }

            // Validation status
            Spacer(Modifier.height(8.dp))
            when {
                phraseValid -> Text(
                    "✓ Valid mnemonic phrase",
                    color = Color(0xFF4CAF50),
                    style = MaterialTheme.typography.bodyMedium,
                    fontWeight = FontWeight.Medium,
                )
                allFilled && !phraseValid -> {
                    val invalidCount = wordValidities.count { it == false }
                    if (invalidCount > 0) {
                        Text(
                            "✗ $invalidCount invalid word${if (invalidCount > 1) "s" else ""}",
                            color = MaterialTheme.colorScheme.error,
                            style = MaterialTheme.typography.bodyMedium,
                        )
                    } else {
                        Text(
                            "✗ Invalid mnemonic checksum",
                            color = MaterialTheme.colorScheme.error,
                            style = MaterialTheme.typography.bodyMedium,
                        )
                    }
                }
                else -> {
                    Text(
                        "$validCount of $restoreWordCount words entered",
                        color = MaterialTheme.colorScheme.onSurfaceVariant,
                        style = MaterialTheme.typography.bodyMedium,
                    )
                }
            }

            Spacer(Modifier.height(4.dp))
            TextButton(onClick = {
                isRestoring = false
                isGenerated = false
                mnemonic = ""
                for (i in 0 until 24) words[i] = ""
            }) {
                Text("Generate a new mnemonic instead")
            }
        }

        if (showPasswordSection) {
            Spacer(Modifier.height(24.dp))

            val context = LocalContext.current
            val canContinue = effectiveMnemonic.isNotEmpty()

            if (isGenerated) {
                OutlinedButton(
                    onClick = { printMnemonic(context, effectiveMnemonic) },
                    modifier = Modifier.fillMaxWidth().height(48.dp),
                ) {
                    Icon(Icons.Default.Print, contentDescription = null, modifier = Modifier.size(20.dp))
                    Spacer(Modifier.width(8.dp))
                    Text("Print Recovery Phrase")
                }
                Spacer(Modifier.height(12.dp))
            }

            Button(
                onClick = { service.setPendingMnemonic(effectiveMnemonic) },
                enabled = canContinue,
                modifier = Modifier.fillMaxWidth().height(56.dp),
            ) {
                Text("Continue", fontSize = 18.sp)
            }
        }
    }
}

/** Print the mnemonic via Android PrintManager — no file saved to disk. */
private fun printMnemonic(context: android.content.Context, mnemonic: String) {
    val printManager = context.getSystemService(android.content.Context.PRINT_SERVICE) as android.print.PrintManager
    val words = mnemonic.split(" ")
    val wordCount = words.size
    val rows = (wordCount + 1) / 2
    val now = java.time.LocalDateTime.now()
    val dateStr = now.format(java.time.format.DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm"))

    // Build 2-column word grid rows
    val gridRows = StringBuilder()
    for (i in 0 until rows) {
        val leftIdx = i
        val rightIdx = i + rows
        val leftNum = String.format("%2d.", leftIdx + 1)
        val leftWord = words.getOrElse(leftIdx) { "" }
        val rightNum = if (rightIdx < wordCount) String.format("%2d.", rightIdx + 1) else ""
        val rightWord = words.getOrElse(rightIdx) { "" }
        gridRows.append("""
            <tr>
                <td class="num">$leftNum</td>
                <td class="word">$leftWord</td>
                <td class="gap"></td>
                <td class="num">$rightNum</td>
                <td class="word">$rightWord</td>
            </tr>
        """)
    }

    // Notes: 3 blank underlines
    val notesLines = (1..3).joinToString("") {
        """<div class="note-line"></div>"""
    }

    val html = """
        <html>
        <head>
        <style>
            @page { size: A4; margin: 25mm 25mm 15mm 25mm; }
            body {
                font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif;
                color: #333;
                margin: 0;
                padding: 0;
                font-size: 10pt;
            }
            h1 {
                font-size: 28pt;
                font-weight: bold;
                margin: 0 0 4mm 0;
            }
            .subtitle {
                font-size: 16pt;
                margin: 0 0 4mm 0;
                font-weight: normal;
            }
            .meta {
                font-size: 10pt;
                color: #666;
                margin: 0 0 2mm 0;
            }
            hr { border: none; border-top: 0.5pt solid #c0c0c0; margin: 6mm 0; }
            .warning-box {
                margin: 4mm 0 6mm 0;
            }
            .warning-title {
                font-size: 12pt;
                font-weight: bold;
                margin-bottom: 3mm;
            }
            .warning-list {
                list-style: none;
                padding-left: 5mm;
                margin: 0;
            }
            .warning-list li {
                font-size: 9pt;
                line-height: 1.8;
            }
            .grid-title {
                font-size: 14pt;
                font-weight: bold;
                margin: 6mm 0 3mm 0;
            }
            .word-grid {
                border: 0.5pt solid #c0c0c0;
                border-collapse: collapse;
                width: 100%;
                margin: 2mm 0;
            }
            .word-grid td {
                padding: 2mm 3mm;
                font-size: 12pt;
                vertical-align: middle;
            }
            .word-grid .num {
                font-family: Helvetica, Arial, sans-serif;
                font-size: 11pt;
                text-align: right;
                width: 10mm;
                color: #666;
            }
            .word-grid .word {
                font-family: "Courier New", Courier, monospace;
                font-size: 12pt;
                width: 55mm;
            }
            .word-grid .gap { width: 10mm; }
            .verify-title {
                font-size: 12pt;
                font-weight: bold;
                margin: 6mm 0 3mm 0;
            }
            .verify-text {
                font-size: 9pt;
                line-height: 1.6;
            }
            .notes-title {
                font-size: 11pt;
                font-weight: bold;
                margin: 6mm 0 3mm 0;
            }
            .note-line {
                border-bottom: 0.5pt solid #ccc;
                height: 8mm;
                margin: 0;
            }
            .footer {
                margin-top: 10mm;
                font-size: 8pt;
                color: #999;
                line-height: 1.6;
            }
        </style>
        </head>
        <body>
            <h1>TIME Coin Wallet</h1>
            <div class="subtitle">Recovery Phrase — Paper Backup</div>
            <div class="meta">Generated: $dateStr</div>
            <div class="meta">$wordCount words</div>
            <hr>

            <div class="warning-box">
                <div class="warning-title">IMPORTANT — READ CAREFULLY</div>
                <ul class="warning-list">
                    <li>• Store this document in a secure location (e.g. safe, safety deposit box).</li>
                    <li>• NEVER share these words with anyone — they give full access to your funds.</li>
                    <li>• Do NOT store this digitally — print and keep the physical copy only.</li>
                    <li>• These words are the ONLY way to recover your wallet if your device is lost.</li>
                    <li>• Anyone with these words can steal all your TIME coins.</li>
                </ul>
            </div>

            <div class="grid-title">Your Recovery Phrase</div>
            <table class="word-grid">
                $gridRows
            </table>

            <div class="verify-title">Verification</div>
            <div class="verify-text">
                After writing down or printing these words, verify them by restoring<br>
                your wallet in the TIME Coin Wallet app using the recovery phrase above.
            </div>

            <div class="notes-title">Notes:</div>
            $notesLines

            <div class="footer">
                TIME Coin Wallet — https://time-coin.io<br>
                This document is confidential. Destroy securely when no longer needed.
            </div>
        </body>
        </html>
    """.trimIndent()

    val webView = android.webkit.WebView(context)
    webView.loadDataWithBaseURL(null, html, "text/html", "UTF-8", null)
    webView.createPrintDocumentAdapter("TIME-Recovery-Phrase").let { adapter ->
        printManager.print("TIME Recovery Phrase", adapter, null)
    }
}

@Composable
private fun MnemonicWordInput(
    number: Int,
    value: String,
    onValueChange: (String) -> Unit,
    isValid: Boolean?,
    focusRequester: FocusRequester,
    isLastField: Boolean,
    onNext: () -> Unit,
    modifier: Modifier = Modifier,
) {
    OutlinedTextField(
        value = value,
        onValueChange = onValueChange,
        modifier = modifier.focusRequester(focusRequester),
        singleLine = true,
        label = { Text("$number") },
        textStyle = MaterialTheme.typography.bodyLarge,
        keyboardOptions = KeyboardOptions(
            capitalization = KeyboardCapitalization.None,
            autoCorrect = false,
            keyboardType = KeyboardType.Text,
            imeAction = if (isLastField) ImeAction.Done else ImeAction.Next,
        ),
        keyboardActions = KeyboardActions(
            onNext = { onNext() },
        ),
        trailingIcon = {
            when {
                value.isBlank() -> {}
                isValid == true -> Icon(
                    Icons.Default.Check,
                    contentDescription = "Valid word",
                    tint = Color(0xFF4CAF50),
                    modifier = Modifier.size(20.dp),
                )
                isValid == false -> Icon(
                    Icons.Default.Close,
                    contentDescription = "Invalid word",
                    tint = MaterialTheme.colorScheme.error,
                    modifier = Modifier.size(20.dp),
                )
            }
        },
        isError = value.isNotBlank() && isValid == false,
    )
}
