package com.timecoin.wallet.ui.screen

import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.text.KeyboardOptions
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.input.KeyboardType
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.timecoin.wallet.crypto.MnemonicHelper
import com.timecoin.wallet.service.WalletService

@Composable
fun MnemonicSetupScreen(service: WalletService) {
    var mnemonic by remember { mutableStateOf("") }
    var isGenerated by remember { mutableStateOf(false) }
    var use24Words by remember { mutableStateOf(false) }
    var password by remember { mutableStateOf("") }
    var passwordConfirm by remember { mutableStateOf("") }
    var showPassword by remember { mutableStateOf(false) }
    var mnemonicInput by remember { mutableStateOf("") }
    var isRestoring by remember { mutableStateOf(false) }
    var inputValid by remember { mutableStateOf<Boolean?>(null) }

    Column(
        modifier = Modifier
            .fillMaxSize()
            .padding(24.dp)
            .verticalScroll(rememberScrollState()),
        horizontalAlignment = Alignment.CenterHorizontally,
    ) {
        Text(
            text = if (isRestoring) "Restore Wallet" else "Create Wallet",
            style = MaterialTheme.typography.headlineMedium,
            fontWeight = FontWeight.Bold,
        )
        Spacer(Modifier.height(24.dp))

        if (!isRestoring && !isGenerated) {
            // Generate new mnemonic
            Row(verticalAlignment = Alignment.CenterVertically) {
                Text("24-word mnemonic")
                Spacer(Modifier.width(8.dp))
                Switch(checked = use24Words, onCheckedChange = { use24Words = it })
            }
            Spacer(Modifier.height(16.dp))

            Button(onClick = {
                mnemonic = MnemonicHelper.generate(if (use24Words) 24 else 12)
                isGenerated = true
            }) {
                Text("Generate Mnemonic")
            }

            Spacer(Modifier.height(24.dp))
            TextButton(onClick = { isRestoring = true }) {
                Text("I already have a mnemonic phrase")
            }
        }

        if (isGenerated) {
            // Display generated mnemonic
            Card(
                modifier = Modifier.fillMaxWidth(),
                colors = CardDefaults.cardColors(
                    containerColor = MaterialTheme.colorScheme.primaryContainer,
                ),
            ) {
                Column(Modifier.padding(16.dp)) {
                    Text(
                        text = "⚠ Write down these words and keep them safe!",
                        style = MaterialTheme.typography.labelLarge,
                        color = MaterialTheme.colorScheme.error,
                        fontWeight = FontWeight.Bold,
                    )
                    Spacer(Modifier.height(12.dp))
                    val words = mnemonic.split(" ")
                    for (i in words.indices step 3) {
                        Row(Modifier.fillMaxWidth()) {
                            for (j in 0 until 3) {
                                val idx = i + j
                                if (idx < words.size) {
                                    Text(
                                        text = "${idx + 1}. ${words[idx]}",
                                        modifier = Modifier.weight(1f),
                                        style = MaterialTheme.typography.bodyMedium,
                                        fontWeight = FontWeight.Medium,
                                    )
                                }
                            }
                        }
                        Spacer(Modifier.height(4.dp))
                    }
                }
            }
        }

        if (isRestoring) {
            // Restore from existing mnemonic
            OutlinedTextField(
                value = mnemonicInput,
                onValueChange = {
                    mnemonicInput = it
                    inputValid = if (it.trim().split("\\s+".toRegex()).size >= 12) {
                        MnemonicHelper.validate(it.trim())
                    } else null
                },
                label = { Text("Enter mnemonic phrase") },
                modifier = Modifier.fillMaxWidth().height(120.dp),
                isError = inputValid == false,
                supportingText = {
                    when (inputValid) {
                        true -> Text("✓ Valid mnemonic", color = MaterialTheme.colorScheme.primary)
                        false -> Text("✗ Invalid mnemonic", color = MaterialTheme.colorScheme.error)
                        null -> Text("Enter 12 or 24 words separated by spaces")
                    }
                },
            )
            if (inputValid == true) {
                mnemonic = mnemonicInput.trim()
                isGenerated = true
            }
        }

        if (isGenerated || (isRestoring && inputValid == true)) {
            Spacer(Modifier.height(24.dp))
            Text(
                text = "Set a password to encrypt your wallet (optional)",
                style = MaterialTheme.typography.bodyMedium,
                textAlign = TextAlign.Center,
            )
            Spacer(Modifier.height(8.dp))

            OutlinedTextField(
                value = password,
                onValueChange = { password = it },
                label = { Text("Password") },
                modifier = Modifier.fillMaxWidth(),
                singleLine = true,
                keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Password),
                visualTransformation = if (showPassword) {
                    androidx.compose.ui.text.input.VisualTransformation.None
                } else {
                    androidx.compose.ui.text.input.PasswordVisualTransformation()
                },
            )
            Spacer(Modifier.height(8.dp))

            if (password.isNotEmpty()) {
                OutlinedTextField(
                    value = passwordConfirm,
                    onValueChange = { passwordConfirm = it },
                    label = { Text("Confirm Password") },
                    modifier = Modifier.fillMaxWidth(),
                    singleLine = true,
                    keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Password),
                    visualTransformation = if (showPassword) {
                        androidx.compose.ui.text.input.VisualTransformation.None
                    } else {
                        androidx.compose.ui.text.input.PasswordVisualTransformation()
                    },
                    isError = passwordConfirm.isNotEmpty() && password != passwordConfirm,
                )
            }

            Spacer(Modifier.height(24.dp))

            val canCreate = mnemonic.isNotEmpty() &&
                (password.isEmpty() || password == passwordConfirm)

            Button(
                onClick = {
                    service.createWallet(
                        mnemonic,
                        password.ifEmpty { null },
                    )
                },
                enabled = canCreate,
                modifier = Modifier.fillMaxWidth().height(56.dp),
            ) {
                Text("Create Wallet", fontSize = 18.sp)
            }
        }
    }
}
