platform :ios, '15.0'

target 'TimeCoinWallet' do
  use_frameworks!

  pod 'Alamofire', '~> 5.8'
  pod 'KeychainSwift', '~> 20.0'

  target 'TimeCoinWalletTests' do
    inherit! :search_paths
  end
end
